import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>My Shops</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/my-shops.svg" />
      </Head>
      <main className='h-screen '>
       

      </main>
    </>
  )
}
